# Generated by Django 4.2.7 on 2023-11-14 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='club',
        ),
    ]
