# Generated by Django 4.2.7 on 2023-11-11 16:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_driver', models.BooleanField(default=False)),
                ('activation_code', models.CharField(blank=True, max_length=10)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=50)),
                ('driver_license', models.CharField(default=None)),
                ('is_car', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='driver/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_user', to='car.car')),
                ('groups', models.ManyToManyField(blank=True, related_name='driver_user_accounts', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='driver_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
