# Generated by Django 4.2.7 on 2023-11-11 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driveruser',
            name='is_driver',
        ),
    ]
